export const IS_VIDEO_ENDED = 'IS_VIDEO_ENDED'
export const IS_CONNECTED_TO_ROOM = 'IS_CONNECTED_TO_ROOM'
export const UPDATE_ROOM_NUMBER = 'UPDATE_ROOM_NUMBER'
export const LAST_SESSION_DATA = 'LAST_SESSION_DATA'